/*
 * Copyright (c) 2024 Yang He
 *
 * TickAuth is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see <https://www.gnu.org/licenses/>.
 */

export class Constants {
  static readonly DOMAIN: number = 0x00101;

  static readonly SECRET_FILE_DIR: string = "/secret.json";

  static readonly DISCLAIMER_TITLE_MARGIN: string = "10%";

  static readonly DISCLAIMER_CONTENT_MARGIN: string = "3%";

  static readonly DISCLAIMER_WIDTH: string = "90%";

  static readonly DISCLAIMER_CONTENT_HEIGHT: string = "65%";

  static readonly DISCLAIMER_BUTTON_WIDTH: string = "47%";

  static readonly DISCLAIMER_BUTTON_ENSEMBLE_WIDTH: string = "92%";

  static readonly DISCLAIMER_BUTTON_ENSEMBLE_HEIGHT: string = "8%";

  static readonly DISCLAIMER_BUTTON_ENSEMBLE_MARGIN: string = "8%";

  static readonly DISCLAIMER_DIALOG_WIDTH: string = "90%";

  static readonly DISCLAIMER_DIALOG_HEIGHT: string = "50%";

  static readonly SETTINGS_USERAUTH: string = "身份认证";

  static readonly USERAUTHVIEW_ITEM_MARGIN: string = "50%";

  static readonly USERAUTHVIEW_SIZE: string = "100%";

  static readonly IMPORTANDEXPORT_ITEM_MARGIN: string = "20%";

  static readonly IMPORTANDEXPORT_ITEM_WIDTH: string = "80%";

  static readonly IMPORTANDEXPORT_SIZE: string = "100%";
}