export class Constants {
  static readonly DOMAIN: number = 0x00101;

  static readonly SECRET_FILE_DIR: string = "/secret.json";

  static readonly DISCLAIMER_TITLE_MARGIN: string = "10%";

  static readonly DISCLAIMER_CONTENT_MARGIN: string = "3%";

  static readonly DISCLAIMER_WIDTH: string = "90%";

  static readonly DISCLAIMER_CONTENT_HEIGHT: string = "65%";

  static readonly DISCLAIMER_BUTTON_WIDTH: string = "47%";

  static readonly DISCLAIMER_BUTTON_ENSEMBLE_WIDTH: string = "92%";

  static readonly DISCLAIMER_BUTTON_ENSEMBLE_HEIGHT: string = "8%";

  static readonly DISCLAIMER_BUTTON_ENSEMBLE_MARGIN: string = "8%";

  static readonly DISCLAIMER_DIALOG_WIDTH: string = "90%";

  static readonly DISCLAIMER_DIALOG_HEIGHT: string = "50%";
}