export class Constants {
  static readonly DOMAIN: number = 0x00302;

  static readonly CUSTOMDIALOG_WARNING_TITLE_MARGIN: string = '10%';

  static readonly CUSTOMDIALOG_WARNING_TEXT_WIDTH: string = '88%';

  static readonly CUSTOMDIALOG_WARNING_BUTTON_WIDTH: string = '40%';

  static readonly CUSTOMDIALOG_WARNING_BUTTON_TOTAL_WIDTH: string = '100%';

  static readonly CUSTOMDIALOG_WARNING_WIDTH: string = '96%';

  static readonly CUSTOMDIALOG_WARNING_HEIGHT: string = '30%';

  static readonly CUSTOMDIALOG_WARNING_BUTTON_TOTAL_MARGIN: string = '8%';
}