/*
 * Copyright (c) 2024 Yang He
 *
 * TickAuth is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see <https://www.gnu.org/licenses/>.
 */

export class Constants {
  static readonly DOMAIN: number = 0x00302;

  static readonly CUSTOMDIALOG_WARNING_TITLE_MARGIN: string = '10%';

  static readonly CUSTOMDIALOG_WARNING_TEXT_WIDTH: string = '88%';

  static readonly CUSTOMDIALOG_WARNING_BUTTON_WIDTH: string = '40%';

  static readonly CUSTOMDIALOG_WARNING_BUTTON_TOTAL_WIDTH: string = '100%';

  static readonly CUSTOMDIALOG_WARNING_WIDTH: string = '96%';

  static readonly CUSTOMDIALOG_WARNING_HEIGHT: string = '30%';

  static readonly CUSTOMDIALOG_WARNING_BUTTON_TOTAL_MARGIN: string = '8%';
}