export class Constants {
  static readonly DOMAIN: number = 0x00201;

  static readonly SECRET_FILE_DIR: string = "/secret.json";

  static readonly HOMEPAGE_SIZE: string = "100%";

  static readonly TOTPVIEW_LIST_SIZE: string = "100%";

  static readonly TOTPVIEW_LIST_SPACE: number = 12;

  static readonly TOTPVIEW_LISTITEM_MAXLINE: number = 1;

  static readonly TOTPVIEW_LISTITEM_TOTP_WIDTH: string = "50%";

  static readonly TOTPVIEW_LISTITEM_TOTP_HEIGHT: string = "50%";

  static readonly TOTPVIEW_LISTITEM_WIDTH: string = "100%";

  static readonly TOTPVIEW_LISTITEM_HEIGHT: string = "13.5%";

  static readonly NOKEYINJSON_IMAGE_MARGIN: string = "7%";

  static readonly ANIMATION_DURING: number = 500;
}