export class Constants {
  static readonly DOMAIN: number = 0x00202;

  static readonly SETTINGSITEM_LIST_SIZE: string = "100%";

  static readonly SETTINGSITEM_LIST_SPACE: number = 12;

  static readonly SETTINGSITEMVIEW_LISTITEM_MAXLINE: number = 1;

  static readonly SETTINGSITEMVIEW_LISTITEM_TITLE_WIDTH: string = "70%";

  static readonly SETTINGSITEMVIEW_LISTITEM_TITLE_HEIGHT: string = "50%";

  static readonly SETTINGSITEMVIEW_LISTITEM_CONTENT_WIDTH: string = "70%";

  static readonly SETTINGSITEMVIEW_LISTITEM_CONTENT_HEIGHT: string = "50%";

  static readonly SETTINGSITEMVIEW_LISTITEM_WIDTH: string = "100%";

  static readonly SETTINGSITEMVIEW_LISTITEM_HEIGHT: string = "10.5%";

  static readonly SETTINGSITEMVIEW_LISTITEM_TEXT_HEIGHT: string = "100%";
}