/*
 * Copyright (c) 2024 Yang He
 *
 * TickAuth is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see <https://www.gnu.org/licenses/>.
 */

export class Constants {
  static readonly DOMAIN: number = 0x00202;

  static readonly SETTINGSITEM_LIST_SIZE: string = "100%";

  static readonly SETTINGSITEM_LIST_SPACE: number = 12;

  static readonly SETTINGSITEMVIEW_LISTITEM_MAXLINE: number = 1;

  static readonly SETTINGSITEMVIEW_LISTITEM_TITLE_WIDTH: string = "70%";

  static readonly SETTINGSITEMVIEW_LISTITEM_TITLE_HEIGHT: string = "50%";

  static readonly SETTINGSITEMVIEW_LISTITEM_CONTENT_WIDTH: string = "70%";

  static readonly SETTINGSITEMVIEW_LISTITEM_CONTENT_HEIGHT: string = "50%";

  static readonly SETTINGSITEMVIEW_LISTITEM_WIDTH: string = "100%";

  static readonly SETTINGSITEMVIEW_LISTITEM_HEIGHT: string = "10.5%";

  static readonly SETTINGSITEMVIEW_LISTITEM_TEXT_HEIGHT: string = "100%";
}